export type Language = {
	english: string;
	native: string;
	group?: string;
};

export const Languages = [
	{ english: 'English', native: 'English', group: 'Common' },
	{ english: 'Mandarin Chinese', native: '普通话', group: 'Common' },
	{ english: 'Hindi', native: 'हिन्दी', group: 'Common' },
	{ english: 'Spanish', native: 'Español', group: 'Common' },
	{ english: 'Standard Arabic', native: 'العربية', group: 'Common' },
	{ english: 'French', native: 'Français', group: 'Common' },
	{ english: 'Bengali', native: 'বাংলা', group: 'Common' },
	{ english: 'Portuguese', native: 'Português', group: 'Common' },
	{ english: 'Russian', native: 'Русский', group: 'Common' },
	{ english: 'Urdu', native: 'اردو', group: 'Common' },
	{ english: 'Indonesian', native: 'Bahasa Indonesia', group: 'Common' },
	{ english: 'German', native: 'Deutsch', group: 'Common' },
	{ english: 'Japanese', native: '日本語', group: 'Common' },
	{ english: 'Nigerian Pidgin', native: 'Naija', group: 'Common' },
	{ english: 'Egyptian Arabic', native: 'مصرى', group: 'Common' },
	{ english: 'Marathi', native: 'मराठी', group: 'Common' },
	{ english: 'Telugu', native: 'తెలుగు', group: 'Common' },
	{ english: 'Turkish', native: 'Türkçe', group: 'Common' },
	{ english: 'Hausa', native: 'Hausa', group: 'Common' },
	{ english: 'Tamil', native: 'தமிழ்', group: 'Common' },
	{ english: 'Yue Chinese', native: '粤语', group: 'Common' },
	{ english: 'Swahili', native: 'Kiswahili', group: 'Common' },
	{ english: 'Vietnamese', native: 'Tiếng Việt', group: 'Common' },
	{ english: 'Wu Chinese', native: '吴语', group: 'Common' },
	{ english: 'Tagalog', native: 'Tagalog', group: 'Common' },
	{ english: 'Western Punjabi', native: 'پنجابی', group: 'Common' },
	{ english: 'Korean', native: '한국어', group: 'Common' },
	{ english: 'Iranian Persian', native: 'فارسی', group: 'Common' },
	{ english: 'Javanese', native: 'ꦧꦱꦗꦮ', group: 'Common' },
	{ english: 'Italian', native: 'Italiano', group: 'Common' },
	{ english: 'Gujarati', native: 'ગુજરાતી', group: 'Common' },
	{ english: 'Thai', native: 'ไทย', group: 'Common' },
	{ english: 'Amharic', native: 'አማርኛ', group: 'Common' },
	{ english: 'Kannada', native: 'ಕನ್ನಡ', group: 'Common' },
	{ english: 'Levantine Arabic', native: 'اللهجة الشامية', group: 'Common' },
	{ english: 'Bhojpuri', native: 'भोजपुरी', group: 'Common' },
	{ english: 'Min Nan Chinese', native: '閩南語', group: 'Common' },

	{ english: 'Ancient Meitei', native: '', group: 'other' },
	{ english: "'Are'are", native: '', group: 'other' },
	{ english: "'Auhelawa", native: '', group: 'other' },
	{ english: "A'Tong", native: '', group: 'other' },
	{ english: 'Aari', native: '', group: 'other' },
	{ english: 'Abanyom', native: '', group: 'other' },
	{ english: 'Abaza', native: '', group: 'other' },
	{ english: 'Abkhaz/Abkhazian', native: '', group: 'other' },
	{ english: 'Abujmaria', native: '', group: 'other' },
	{ english: 'Acehnese', native: '', group: 'other' },
	{ english: 'Adele', native: '', group: 'other' },
	{ english: 'Adyghe', native: '', group: 'other' },
	{ english: 'Afar', native: '', group: 'other' },
	{ english: 'Afrikaans', native: '', group: 'other' },
	{ english: 'Afro-Seminole Creole', native: '', group: 'other' },
	{ english: 'Aimaq/Barbari', native: '', group: 'other' },
	{ english: 'Aini', native: '', group: 'other' },
	{ english: 'Ainu', native: '', group: 'other' },
	{ english: 'Akan', native: '', group: 'other' },
	{ english: 'Akawaio', native: '', group: 'other' },
	{ english: 'Aklanon', native: '', group: 'other' },
	{ english: 'Albanian', native: '', group: 'other' },
	{ english: 'Aleut', native: '', group: 'other' },
	{ english: 'Algonquin', native: '', group: 'other' },
	{ english: 'Alsatian', native: '', group: 'other' },
	{ english: 'Altay', native: '', group: 'other' },
	{ english: 'Alutor', native: '', group: 'other' },
	{ english: 'Anda', native: '', group: 'other' },
	{ english: 'Amdang', native: '', group: 'other' },
	{ english: 'Angika', native: '', group: 'other' },
	{ english: 'Anyin', native: '', group: 'other' },
	{ english: 'Ao', native: '', group: 'other' },
	{ english: 'A-Pucikwar', native: '', group: 'other' },
	{ english: 'Aragonese', native: '', group: 'other' },
	{ english: 'Aramaic', native: '', group: 'other' },
	{ english: 'Are', native: '', group: 'other' },
	{ english: 'Argobba', native: '', group: 'other' },
	{ english: 'Aromanian/Macedo-Romanian', native: '', group: 'other' },
	{ english: 'Armenian', native: '', group: 'other' },
	{ english: 'Arvanitic', native: '', group: 'other' },
	{ english: 'Ashkun', native: '', group: 'other' },
	{ english: 'Assamese', native: '', group: 'other' },
	{ english: 'Assyrian Neo-Aramaic', native: '', group: 'other' },
	{ english: 'Ateso/Teso', native: '', group: 'other' },
	{ english: 'Asi', native: '', group: 'other' },
	{ english: 'Asturian', native: '', group: 'other' },
	{ english: 'Auslan', native: '', group: 'other' },
	{ english: 'Austro-Bavarian', native: '', group: 'other' },
	{ english: 'Avar', native: '', group: 'other' },
	{ english: 'Avestan', native: '', group: 'other' },
	{ english: 'Awadhi', native: '', group: 'other' },
	{ english: 'Aymara', native: '', group: 'other' },
	{ english: 'Azerbaijani', native: '', group: 'other' },
	{ english: 'Badaga', native: '', group: 'other' },
	{ english: 'Badeshi', native: '', group: 'other' },
	{ english: 'Bahnar', native: '', group: 'other' },
	{ english: 'Balinese', native: '', group: 'other' },
	{ english: 'Balochi', native: '', group: 'other' },
	{ english: 'Balti', native: '', group: 'other' },
	{ english: 'Bambara/Bamanankan', native: '', group: 'other' },
	{ english: 'Banjar', native: '', group: 'other' },
	{ english: 'Banyumasan', native: '', group: 'other' },
	{ english: 'Bartangi', native: '', group: 'other' },
	{ english: 'Basaa', native: '', group: 'other' },
	{ english: 'Bashkardi', native: '', group: 'other' },
	{ english: 'Bashkir', native: '', group: 'other' },
	{ english: 'Basque', native: '', group: 'other' },
	{ english: 'Batak Karo', native: '', group: 'other' },
	{ english: 'Batak Toba', native: '', group: 'other' },
	{ english: 'Bats', native: '', group: 'other' },
	{ english: 'Beja', native: '', group: 'other' },
	{ english: 'Belarusian', native: '', group: 'other' },
	{ english: 'Belhare', native: '', group: 'other' },
	{ english: 'Berta', native: '', group: 'other' },
	{ english: 'Bemba', native: '', group: 'other' },
	{ english: 'Bezhta', native: '', group: 'other' },
	{ english: 'Betawi', native: '', group: 'other' },
	{ english: 'Bete', native: '', group: 'other' },
	{ english: 'Bhili', native: '', group: 'other' },
	{ english: 'Bijil Neo-Aramaic', native: '', group: 'other' },
	{ english: 'Bikol', native: '', group: 'other' },
	{ english: 'Bikya/Furu', native: '', group: 'other' },
	{ english: 'Bissa', native: '', group: 'other' },
	{ english: 'Blackfoot', native: '', group: 'other' },
	{ english: 'Boholano', native: '', group: 'other' },
	{ english: 'Bohtan Neo-Aramaic', native: '', group: 'other' },
	{ english: 'Bonan/Paoan', native: '', group: 'other' },
	{ english: 'Bororo', native: '', group: 'other' },
	{ english: 'Bodo', native: '', group: 'other' },
	{ english: 'Bosnian', native: '', group: 'other' },
	{ english: 'Brahui', native: '', group: 'other' },
	{ english: 'Breton', native: '', group: 'other' },
	{ english: 'British Sign Language', native: '', group: 'other' },
	{ english: 'Bua', native: '', group: 'other' },
	{ english: 'Buginese', native: '', group: 'other' },
	{ english: 'Bukusu', native: '', group: 'other' },
	{ english: 'Bulgarian', native: '', group: 'other' },
	{ english: 'Bunjevac', native: '', group: 'other' },
	{ english: 'Burmese', native: '', group: 'other' },
	{ english: 'Burushaski', native: '', group: 'other' },
	{ english: 'Buryat', native: '', group: 'other' },
	{ english: 'Caddo', native: '', group: 'other' },
	{ english: 'Cahuilla', native: '', group: 'other' },
	{ english: 'Caluyanon/Caluyanun', native: '', group: 'other' },
	{ english: 'Cantonese', native: '', group: 'other' },
	{ english: 'Catalan', native: '', group: 'other' },
	{ english: 'Cayuga', native: '', group: 'other' },
	{ english: 'Cebuano', native: '', group: 'other' },
	{ english: 'Chabacano/Chavacano', native: '', group: 'other' },
	{ english: 'Chaga/Kichagga', native: '', group: 'other' },
	{ english: 'Chakma', native: '', group: 'other' },
	{ english: 'Chaldean Neo-Aramaic', native: '', group: 'other' },
	{ english: 'Chamorro', native: '', group: 'other' },
	{ english: 'Chaouia/Tachawit', native: '', group: 'other' },
	{ english: 'Chechen', native: '', group: 'other' },
	{ english: 'Chenchu', native: '', group: 'other' },
	{ english: 'Chenoua', native: '', group: 'other' },
	{ english: 'Cherokee', native: '', group: 'other' },
	{ english: 'Cheyenne', native: '', group: 'other' },
	{ english: 'Chhattisgarhi', native: '', group: 'other' },
	{ english: 'Chickasaw', native: '', group: 'other' },
	{ english: 'Chintang/Chhintang', native: '', group: 'other' },
	{ english: 'Chilcotin', native: '', group: 'other' },
	{ english: 'Chiricahua/Mescalero-Chiricahua Apache', native: '', group: 'other' },
	{ english: 'Chichewa/Nyanja', native: '', group: 'other' },
	{ english: 'Chipewyan', native: '', group: 'other' },
	{ english: 'Chittagonian', native: '', group: 'other' },
	{ english: 'Choctaw', native: '', group: 'other' },
	{ english: 'Chorasmian/Khwarezmian', native: '', group: 'other' },
	{ english: 'Chukchi/Chukot', native: '', group: 'other' },
	{ english: 'Chulym', native: '', group: 'other' },
	{ english: 'Church Slavonic', native: '', group: 'other' },
	{ english: 'Chuukese/Trukese', native: '', group: 'other' },
	{ english: 'Chuvash', native: '', group: 'other' },
	{ english: 'Cocoma/Cocama', native: '', group: 'other' },
	{ english: 'Cocopa', native: '', group: 'other' },
	{ english: "Coeur d'Alene", native: '', group: 'other' },
	{ english: 'Comanche', native: '', group: 'other' },
	{ english: 'Comorian', native: '', group: 'other' },
	{ english: 'Cornish', native: '', group: 'other' },
	{ english: 'Corsican', native: '', group: 'other' },
	{ english: 'Cree', native: '', group: 'other' },
	{ english: 'Crimean Tatar/Crimean Turkish', native: '', group: 'other' },
	{ english: 'Croatian', native: '', group: 'other' },
	{ english: 'Cuyonon', native: '', group: 'other' },
	{ english: 'Czech', native: '', group: 'other' },

	{ english: 'Dagbani', native: '', group: 'other' },
	{ english: 'Dahlik', native: '', group: 'other' },
	{ english: 'Dalecarlian', native: '', group: 'other' },
	{ english: 'Dameli', native: '', group: 'other' },
	{ english: 'Danish', native: '', group: 'other' },
	{ english: 'Dargin', native: '', group: 'other' },
	{ english: 'Dakota', native: '', group: 'other' },
	{ english: 'Dari', native: '', group: 'other' },
	{ english: 'Dari-Persian', native: '', group: 'other' },
	{ english: 'Daur/Dagur', native: '', group: 'other' },
	{ english: "Dena'ina/Tanaina", native: '', group: 'other' },
	{ english: 'Dhatki', native: '', group: 'other' },
	{ english: 'Dhivehi/Maldivian', native: '', group: 'other' },
	{ english: 'Dida', native: '', group: 'other' },
	{ english: 'Dioula/Jula', native: '', group: 'other' },
	{ english: 'Dogri', native: '', group: 'other' },
	{ english: 'Dogrib/Tli Cho', native: '', group: 'other' },
	{ english: 'Dolgan', native: '', group: 'other' },
	{ english: 'Domaaki/Dumaki', native: '', group: 'other' },
	{ english: 'Dongxiang/Santa', native: '', group: 'other' },
	{ english: 'Duala', native: '', group: 'other' },
	{ english: 'Dungan', native: '', group: 'other' },
	{ english: 'Dutch', native: '', group: 'other' },
	{ english: 'Dzhidi/Judeo-Persian', native: '', group: 'other' },
	{ english: 'Dzongkha', native: '', group: 'other' },

	{ english: 'Eastern Yugur', native: '', group: 'other' },
	{ english: 'Edo', native: '', group: 'other' },
	{ english: 'Efik', native: '', group: 'other' },
	{ english: 'Esan', native: '', group: 'other' },
	{ english: 'Ekoti', native: '', group: 'other' },
	{ english: 'Enets/Yenisey Samoyed', native: '', group: 'other' },
	{ english: 'Erzya', native: '', group: 'other' },
	{ english: 'Esperanto', native: '', group: 'other' },
	{ english: 'Estonian', native: '', group: 'other' },
	{ english: 'Even', native: '', group: 'other' },
	{ english: 'Evenk/Evenki', native: '', group: 'other' },
	{ english: 'Ewe', native: '', group: 'other' },
	{ english: 'Extremaduran', native: '', group: 'other' },

	{ english: 'Faroese language', native: '', group: 'other' },
	{ english: 'Fang', native: '', group: 'other' },
	{ english: 'Fijian', native: '', group: 'other' },
	{ english: 'Filipino', native: '', group: 'other' },
	{ english: 'Finnish', native: '', group: 'other' },
	{ english: 'Flemish language', native: '', group: 'other' },
	{ english: 'Fon', native: '', group: 'other' },
	{ english: 'Franco-Provençal/Arpitan', native: '', group: 'other' },
	{ english: 'Frisian, North', native: '', group: 'other' },
	{ english: 'Frisian, Saterland', native: '', group: 'other' },
	{ english: 'Frisian, West', native: '', group: 'other' },
	{ english: 'Friulian', native: '', group: 'other' },
	{ english: 'Fula/Fulfulde/Fulani', native: '', group: 'other' },
	{ english: 'Fur', native: '', group: 'other' },

	{ english: 'Ga', native: '', group: 'other' },
	{ english: 'Gadaba', native: '', group: 'other' },
	{ english: 'Gagauz', native: '', group: 'other' },
	{ english: 'Galician', native: '', group: 'other' },
	{ english: 'Gallo', native: '', group: 'other' },
	{ english: 'Gan', native: '', group: 'other' },
	{ english: 'Ganda', native: '', group: 'other' },
	{ english: 'Gangte', native: '', group: 'other' },
	{ english: 'Garhwali', native: '', group: 'other' },
	{ english: 'Gayo', native: '', group: 'other' },
	{ english: 'Gen/Gẽ/Mina', native: '', group: 'other' },
	{ english: 'Georgian', native: '', group: 'other' },
	{ english: 'Gikuyu/Kikuyu', native: '', group: 'other' },
	{ english: 'Gilbertese/Kiribati', native: '', group: 'other' },
	{ english: 'Gileki', native: '', group: 'other' },
	{ english: 'Goaria', native: '', group: 'other' },
	{ english: 'Gondi', native: '', group: 'other' },
	{ english: 'Gorani/Gurani', native: '', group: 'other' },
	{ english: 'Gowro', native: '', group: 'other' },
	{ english: 'Gawar-Bati/Gowari/Narsati', native: '', group: 'other' },
	{ english: 'Greek', native: '', group: 'other' },
	{ english: 'Guaraní', native: '', group: 'other' },
	{ english: 'Guinea-Bissau Creole', native: '', group: 'other' },
	{ english: 'Gula Iro/Kulaal', native: '', group: 'other' },
	{ english: 'Gullah/Sea Island Creole English', native: '', group: 'other' },
	{ english: 'Gusii', native: '', group: 'other' },
	{ english: "Gwich'in", native: '', group: 'other' },

	{ english: 'Hadza', native: '', group: 'other' },
	{ english: 'Haida', native: '', group: 'other' },
	{ english: 'Haitian Creole', native: '', group: 'other' },
	{ english: 'Hakka', native: '', group: 'other' },
	{ english: 'Hän', native: '', group: 'other' },
	{ english: 'Harari', native: '', group: 'other' },
	{ english: 'Harauti', native: '', group: 'other' },
	{ english: 'Harsusi', native: '', group: 'other' },
	{ english: 'Haryanavi', native: '', group: 'other' },
	{ english: 'Harzani', native: '', group: 'other' },
	{ english: 'Havasupai/Upland Yuman', native: '', group: 'other' },
	{ english: 'Hawaiian', native: '', group: 'other' },
	{ english: 'Hazaragi', native: '', group: 'other' },
	{ english: 'Hebrew', native: '', group: 'other' },
	{ english: 'Herero', native: '', group: 'other' },
	{ english: 'Hértevin', native: '', group: 'other' },
	{ english: 'Hiligaynon', native: '', group: 'other' },
	{ english: 'Hinukh', native: '', group: 'other' },
	{ english: 'Hiri Motu', native: '', group: 'other' },
	{ english: 'Hixkaryana', native: '', group: 'other' },
	{ english: 'Hmong', native: '', group: 'other' },
	{ english: 'Ho', native: '', group: 'other' },
	{ english: 'Hobyót', native: '', group: 'other' },
	{ english: 'Hopi', native: '', group: 'other' },
	{ english: 'Hulaulá', native: '', group: 'other' },
	{ english: 'Hungarian', native: '', group: 'other' },
	{ english: 'Hunsrik', native: '', group: 'other' },
	{ english: 'Hutterite German', native: '', group: 'other' },

	{ english: 'Ibibio', native: '', group: 'other' },
	{ english: 'Iban', native: '', group: 'other' },
	{ english: 'Ibanag', native: '', group: 'other' },
	{ english: 'Icelandic', native: '', group: 'other' },
	{ english: 'Ido', native: '', group: 'other' },
	{ english: 'Ifè', native: '', group: 'other' },
	{ english: 'Igbo/Ibo/Biafra', native: '', group: 'other' },
	{ english: 'Ikalanga/Kalanga', native: '', group: 'other' },
	{ english: 'Ili Turki', native: '', group: 'other' },
	{ english: 'Ilokano/Ilocano', native: '', group: 'other' },
	{ english: 'Inari Sami', native: '', group: 'other' },
	{ english: 'Ingrian/Izhorian', native: '', group: 'other' },
	{ english: 'Ingush', native: '', group: 'other' },
	{ english: 'Interlingua', native: '', group: 'other' },
	{ english: 'Inuktitut', native: '', group: 'other' },
	{ english: 'Inupiaq', native: '', group: 'other' },
	{ english: 'Inuvialuktun', native: '', group: 'other' },
	{ english: 'Iraqw', native: '', group: 'other' },
	{ english: 'Irish/Irish Gaelic', native: '', group: 'other' },
	{ english: 'Irula', native: '', group: 'other' },
	{ english: 'Isan/Northeastern Thai', native: '', group: 'other' },
	{ english: 'Ishkashimi/Ishkashmi', native: '', group: 'other' },
	{ english: 'Istro-Romanian', native: '', group: 'other' },
	{ english: 'Itelmen/Kamchadal', native: '', group: 'other' },

	{ english: 'Jacaltec/Jakalteko', native: '', group: 'other' },
	{ english: 'Jalaa', native: '', group: 'other' },
	{ english: 'Jaqaru', native: '', group: 'other' },
	{ english: 'Jarai', native: '', group: 'other' },
	{ english: 'Jibbali/Shehri', native: '', group: 'other' },
	{ english: 'Jewish Babylonian Aramaic', native: '', group: 'other' },
	{ english: 'Jicarilla Apache', native: '', group: 'other' },
	{ english: 'Juang', native: '', group: 'other' },
	{ english: 'Jurchen', native: '', group: 'other' },

	{ english: 'Kabardian', native: '', group: 'other' },
	{ english: 'Kabyle', native: '', group: 'other' },
	{ english: 'Kachin/Jingpo', native: '', group: 'other' },
	{ english: 'Kalaallisut/Greenlandic', native: '', group: 'other' },
	{ english: 'Kalami/Gawri/Dirwali', native: '', group: 'other' },
	{ english: 'Kalasha', native: '', group: 'other' },
	{ english: 'Kalmyk/Oirat', native: '', group: 'other' },
	{ english: 'Kalto/Nahali', native: '', group: 'other' },
	{ english: 'Kankanai/Kankanaey', native: '', group: 'other' },
	{ english: 'Kaonde/Chikaonde', native: '', group: 'other' },
	{ english: 'Kapampangan', native: '', group: 'other' },
	{ english: 'Karachay-Balkar', native: '', group: 'other' },
	{ english: 'Karagas', native: '', group: 'other' },
	{ english: 'Karaim', native: '', group: 'other' },
	{ english: 'Karakalpak', native: '', group: 'other' },
	{ english: 'Karelian', native: '', group: 'other' },
	{ english: 'Kashmiri', native: '', group: 'other' },
	{ english: 'Kashubian', native: '', group: 'other' },
	{ english: 'Kazakh', native: '', group: 'other' },
	{ english: 'Kerek', native: '', group: 'other' },
	{ english: 'Ket', native: '', group: 'other' },
	{ english: 'Khakas', native: '', group: 'other' },
	{ english: 'Khalaj', native: '', group: 'other' },
	{ english: 'Kham/Sheshi', native: '', group: 'other' },
	{ english: 'Khandeshi', native: '', group: 'other' },
	{ english: 'Khanty/Ostyak', native: '', group: 'other' },
	{ english: 'Khasi', native: '', group: 'other' },
	{ english: 'Khitan', native: '', group: 'other' },
	{ english: 'Khmer', native: '', group: 'other' },
	{ english: 'Khmu', native: '', group: 'other' },
	{ english: 'Khowar', native: '', group: 'other' },
	{ english: 'Kildin Sami', native: '', group: 'other' },
	{ english: 'Kimatuumbi', native: '', group: 'other' },
	{ english: 'Kinaray-a/Hiraya', native: '', group: 'other' },
	{ english: 'Kinyarwanda', native: '', group: 'other' },
	{ english: 'Kirombo', native: '', group: 'other' },
	{ english: 'Kirundi', native: '', group: 'other' },
	{ english: 'Kivunjo', native: '', group: 'other' },
	{ english: 'Klallam/Clallam', native: '', group: 'other' },
	{ english: 'Kodava Takk/Kodagu/Coorgi', native: '', group: 'other' },
	{ english: 'Kohistani/Khili', native: '', group: 'other' },
	{ english: 'Kolami', native: '', group: 'other' },
	{ english: 'Komi/Komi-Zyrian', native: '', group: 'other' },
	{ english: 'Konkani', native: '', group: 'other' },
	{ english: 'Kongo/Kikongo', native: '', group: 'other' },
	{ english: 'Koraga', native: '', group: 'other' },
	{ english: 'Korandje', native: '', group: 'other' },
	{ english: 'Korku', native: '', group: 'other' },
	{ english: 'Korowai', native: '', group: 'other' },
	{ english: 'Korwa', native: '', group: 'other' },
	{ english: 'Koryak', native: '', group: 'other' },
	{ english: 'Kosraean', native: '', group: 'other' },
	{ english: 'Kota', native: '', group: 'other' },
	{ english: 'Koyra Chiini/Western Songhay', native: '', group: 'other' },
	{ english: 'Koy Sanjaq Surat', native: '', group: 'other' },
	{ english: 'Koya', native: '', group: 'other' },
	{ english: 'Krymchak/Judeo-Crimean Tatar', native: '', group: 'other' },
	{ english: 'Kujarge', native: '', group: 'other' },
	{ english: 'Kui', native: '', group: 'other' },
	{ english: 'Kumauni', native: '', group: 'other' },
	{ english: 'Kumyk', native: '', group: 'other' },
	{ english: 'Kumzari', native: '', group: 'other' },
	{ english: '!Kung', native: '', group: 'other' },
	{ english: 'Kurdish', native: '', group: 'other' },
	{ english: 'Kurukh/Kurux', native: '', group: 'other' },
	{ english: 'Kusunda', native: '', group: 'other' },
	{ english: 'Kutenai/Kootenay/Ktunaxa', native: '', group: 'other' },
	{ english: 'Kwanyama/Ovambo', native: '', group: 'other' },
	{ english: 'Kxoe', native: '', group: 'other' },
	{ english: 'Kyrgyz/Kirghiz', native: '', group: 'other' },

	{ english: 'Laal', native: '', group: 'other' },
	{ english: 'Ladakhi', native: '', group: 'other' },
	{ english: 'Ladin', native: '', group: 'other' },
	{ english: 'Laki', native: '', group: 'other' },
	{ english: 'Lakota/Lakhota/Teton', native: '', group: 'other' },
	{ english: 'Lambadi/Lamani/Banjari', native: '', group: 'other' },
	{ english: 'Lao/Laotian', native: '', group: 'other' },
	{ english: 'Larestani', native: '', group: 'other' },
	{ english: 'Latin', native: '', group: 'other' },
	{ english: 'Latvian', native: '', group: 'other' },
	{ english: 'Laz/Lazuri', native: '', group: 'other' },
	{ english: 'Leonese', native: '', group: 'other' },
	{ english: 'Lepcha', native: '', group: 'other' },
	{ english: 'Lezgi/Agul', native: '', group: 'other' },
	{ english: 'Ligbi/Ligby', native: '', group: 'other' },
	{ english: 'Limbu', native: '', group: 'other' },
	{ english: 'Limburgish', native: '', group: 'other' },
	{ english: 'Lingala', native: '', group: 'other' },
	{ english: 'Lipan Apache', native: '', group: 'other' },
	{ english: 'Lisan al-Dawat', native: '', group: 'other' },
	{ english: 'Lishana Deni', native: '', group: 'other' },
	{ english: 'Lishanid Noshan/Lishana Didan', native: '', group: 'other' },
	{ english: 'Lithuanian', native: '', group: 'other' },
	{ english: 'Livonian language/Liv', native: '', group: 'other' },
	{ english: 'Lombard', native: '', group: 'other' },
	{ english: 'Lotha', native: '', group: 'other' },
	{ english: 'Low German/Low Saxon', native: '', group: 'other' },
	{ english: 'Lower Sorbian', native: '', group: 'other' },
	{ english: 'Lozi/Silozi', native: '', group: 'other' },
	{ english: 'Ludic/Ludian', native: '', group: 'other' },
	{ english: 'Lunda/Chilunda', native: '', group: 'other' },
	{ english: 'Luo', native: '', group: 'other' },
	{ english: 'Luri', native: '', group: 'other' },
	{ english: 'Lushootseed', native: '', group: 'other' },
	{ english: 'Lusoga/Soga', native: '', group: 'other' },
	{ english: 'Luvale', native: '', group: 'other' },
	{ english: 'Luwati', native: '', group: 'other' },
	{ english: 'Luxembourgish', native: '', group: 'other' },
	{ english: 'Lycian', native: '', group: 'other' },
	{ english: 'Lydian', native: '', group: 'other' },

	{ english: 'Macedonian', native: '', group: 'other' },
	{ english: 'Magadhi', native: '', group: 'other' },
	{ english: 'Maguindanao', native: '', group: 'other' },
	{ english: 'Maithili', native: '', group: 'other' },
	{ english: 'Makasar', native: '', group: 'other' },
	{ english: 'Makhuwa/Makua', native: '', group: 'other' },
	{ english: 'Makhuwa-Meetto', native: '', group: 'other' },
	{ english: 'Malagasy', native: '', group: 'other' },
	{ english: 'Malay', native: '', group: 'other' },
	{ english: 'Malayalam', native: '', group: 'other' },
	{ english: 'Maltese', native: '', group: 'other' },
	{ english: 'Malto/Sauria Paharia', native: '', group: 'other' },
	{ english: 'Malvi/Malavi/Ujjaini', native: '', group: 'other' },
	{ english: 'Mam', native: '', group: 'other' },
	{ english: 'Manchu', native: '', group: 'other' },
	{ english: 'Mandaic', native: '', group: 'other' },
	{ english: 'Mandinka', native: '', group: 'other' },
	{ english: 'Mansi/Vogul', native: '', group: 'other' },
	{ english: 'Manx', native: '', group: 'other' },
	{ english: 'Manyika', native: '', group: 'other' },
	{ english: 'Maori', native: '', group: 'other' },
	{ english: 'Mapudungun/Mapuche', native: '', group: 'other' },
	{ english: 'Maranao', native: '', group: 'other' },
	{ english: 'Mari/Cheremis', native: '', group: 'other' },
	{ english: 'Maria', native: '', group: 'other' },
	{ english: 'Marquesan', native: '', group: 'other' },
	{ english: 'Marshallese/Ebon', native: '', group: 'other' },
	{ english: 'Masaba', native: '', group: 'other' },
	{ english: 'Masbatenyo/Minasbate (Malayo-Polynesian', native: '', group: 'other' },
	{ english: 'Meitei/Manipuri/Meithei', native: '', group: 'other' },
	{ english: 'Mauritian Creole/Morisyen', native: '', group: 'other' },
	{ english: 'Maya', native: '', group: 'other' },
	{ english: 'Mazandarani/Tabari(Iranian)', native: '', group: 'other' },
	{ english: 'Meänkieli/Tornedalen Finnish', native: '', group: 'other' },
	{ english: 'Megleno-Romanian', native: '', group: 'other' },
	{ english: 'Megrelian/Mingrelian', native: '', group: 'other' },
	{ english: 'Mehri/Mahri', native: '', group: 'other' },
	{ english: 'Menominee', native: '', group: 'other' },
	{ english: 'Mentawai', native: '', group: 'other' },
	{ english: 'Meroitic', native: '', group: 'other' },
	{ english: 'Mescalero Apache', native: '', group: 'other' },
	{ english: 'Meru/Kimeru', native: '', group: 'other' },
	{ english: 'Michif', native: '', group: 'other' },
	{ english: 'Mikasuki/Miccosukee', native: '', group: 'other' },
	{ english: "Mi'kmaq/Micmac", native: '', group: 'other' },
	{ english: 'Minangkabau', native: '', group: 'other' },
	{ english: 'Mirandese', native: '', group: 'other' },
	{ english: 'Mobilian Jargon', native: '', group: 'other' },
	{ english: 'Moghol', native: '', group: 'other' },
	{ english: 'Mohawk', native: '', group: 'other' },
	{ english: 'Moksha', native: '', group: 'other' },
	{ english: 'Molengue', native: '', group: 'other' },
	{ english: 'Mon', native: '', group: 'other' },
	{ english: 'Mongolian', native: '', group: 'other' },
	{ english: 'Mono', native: '', group: 'other' },
	{ english: 'Mono', native: '', group: 'other' },
	{ english: 'Mono', native: '', group: 'other' },
	{ english: 'Montagnais', native: '', group: 'other' },
	{ english: 'Montenegrin', native: '', group: 'other' },
	{ english: 'Motu', native: '', group: 'other' },
	{ english: 'Muher', native: '', group: 'other' },
	{ english: 'Mundari', native: '', group: 'other' },
	{ english: 'Munji', native: '', group: 'other' },
	{ english: 'Muria', native: '', group: 'other' },
	{ english: 'Template:Mwaghavul Template:Myene', native: '', group: 'other' },
	{ english: '', native: '', group: 'other' },

	{ english: 'Nafaanra', native: '', group: 'other' },
	{ english: 'Nagarchal', native: '', group: 'other' },
	{ english: 'Nahuatl', native: '', group: 'other' },
	{ english: 'Nama', native: '', group: 'other' },
	{ english: 'Nanai', native: '', group: 'other' },
	{ english: 'Nauruan', native: '', group: 'other' },
	{ english: 'Navajo/Navaho', native: '', group: 'other' },
	{ english: 'Ndau/Southeast Shona', native: '', group: 'other' },
	{ english: 'Ndebele', native: '', group: 'other' },
	{ english: 'Ndonga', native: '', group: 'other' },
	{ english: 'Neapolitan', native: '', group: 'other' },
	{ english: 'Negidal', native: '', group: 'other' },
	{ english: 'Nepal Bhasa/Newari', native: '', group: 'other' },
	{ english: 'Nepali', native: '', group: 'other' },
	{ english: 'Nihali/Nahali', native: '', group: 'other' },
	{ english: 'Nganasan/Tavgi', native: '', group: 'other' },
	{ english: 'Ngumba', native: '', group: 'other' },
	{ english: 'Nheengatu/Geral/Modern Tupí', native: '', group: 'other' },
	{ english: 'Nias', native: '', group: 'other' },
	{ english: 'Niellim', native: '', group: 'other' },
	{ english: 'Nisenan', native: '', group: 'other' },
	{ english: 'Niuean/Niue', native: '', group: 'other' },
	{ english: 'Nivkh/Gilyak', native: '', group: 'other' },
	{ english: 'Nogai', native: '', group: 'other' },
	{ english: 'Norfuk/Norfolk/Pitcairn-Norfolk', native: '', group: 'other' },
	{ english: 'Northern Sami', native: '', group: 'other' },
	{ english: 'Northern Sotho/Sepedi', native: '', group: 'other' },
	{ english: 'Northern Straits Salish)', native: '', group: 'other' },
	{ english: 'Northern Yukaghir', native: '', group: 'other' },
	{ english: 'Norwegian', native: '', group: 'other' },
	{ english: 'Nuer', native: '', group: 'other' },
	{ english: 'Nuxálk/Bella Coola', native: '', group: 'other' },
	{ english: 'Nyabwa', native: '', group: 'other' },
	{ english: 'Nyah Kur', native: '', group: 'other' },
	{ english: 'Nyangumarta', native: '', group: 'other' },
	{ english: 'Nyoro', native: '', group: 'other' },
	{ english: 'Nǀu', native: '', group: 'other' },

	{ english: 'Occitan/Provençal', native: '', group: 'other' },
	{ english: 'Ojibwe/Ojibwa/Chippewa', native: '', group: 'other' },
	{ english: 'Okinawan', native: '', group: 'other' },
	{ english: 'Olonets Karelian/Liv/Livvi', native: '', group: 'other' },
	{ english: 'Omagua', native: '', group: 'other' },
	{ english: 'Ongota', native: '', group: 'other' },
	{ english: 'Odia', native: '', group: 'other' },
	{ english: 'Ormuri', native: '', group: 'other' },
	{ english: 'Oroch', native: '', group: 'other' },
	{ english: 'Orok', native: '', group: 'other' },
	{ english: 'Oromo/Afaan Oromoo', native: '', group: 'other' },
	{ english: 'Ossetic/Ossetian', native: '', group: 'other' },

	{ english: 'Páez/Nasa Yuwe', native: '', group: 'other' },
	{ english: 'Palauan', native: '', group: 'other' },
	{ english: 'Pangasinan', native: '', group: 'other' },
	{ english: 'Papiamento/Papiamentu', native: '', group: 'other' },
	{ english: 'Parachi', native: '', group: 'other' },
	{ english: 'Parya', native: '', group: 'other' },
	{ english: 'Pashto/Pushto/Pashtu', native: '', group: 'other' },
	{ english: 'Pennsylvania Dutch/Pennsylvania German', native: '', group: 'other' },
	{ english: 'Phalura', native: '', group: 'other' },
	{ english: 'Phuthi', native: '', group: 'other' },
	{ english: 'Pig Latin', native: '', group: 'other' },
	{ english: 'Picard', native: '', group: 'other' },
	{ english: 'Pirahã', native: '', group: 'other' },
	{ english: 'Plautdietsch/Mennonite Low German', native: '', group: 'other' },
	{ english: 'Polish', native: '', group: 'other' },
	{ english: 'Pothohari/Pahari-Potwari', native: '', group: 'other' },
	{ english: 'Pradhan/Pardhan', native: '', group: 'other' },
	{ english: 'Puelche', native: '', group: 'other' },
	{ english: 'Puma', native: '', group: 'other' },

	{ english: 'Qashqai/Ghashghai', native: '', group: 'other' },
	{ english: 'Quechua', native: '', group: 'other' },

	{ english: 'Rajasthani', native: '', group: 'other' },
	{ english: 'Ratagnon/Datagnon/Latagnun', native: '', group: 'other' },
	{ english: 'Réunion Creole/Bourbonnais', native: '', group: 'other' },
	{ english: 'Romanian', native: '', group: 'other' },
	{ english: 'Romansh/Rhaeto-Romance', native: '', group: 'other' },
	{ english: 'Romany', native: '', group: 'other' },
	{ english: 'Romblomanon', native: '', group: 'other' },
	{ english: 'Rotokas', native: '', group: 'other' },
	{ english: 'Runyankole language/Nyankore', native: '', group: 'other' },
	{ english: 'Ruthenian/Rusyn/Carpathian', native: '', group: 'other' },

	{ english: 'Sadri', native: '', group: 'other' },
	{ english: 'Salar', native: '', group: 'other' },
	{ english: 'Samoan', native: '', group: 'other' },
	{ english: 'Sandawe', native: '', group: 'other' },
	{ english: 'Sango', native: '', group: 'other' },
	{ english: 'Sanskrit', native: '', group: 'other' },
	{ english: 'Santali', native: '', group: 'other' },
	{ english: 'Sara', native: '', group: 'other' },
	{ english: 'Saraiki/Seraiki/Siraiki', native: '', group: 'other' },
	{ english: 'Saramaccan', native: '', group: 'other' },
	{ english: 'Sardinian', native: '', group: 'other' },
	{ english: 'Sarikoli', native: '', group: 'other' },
	{ english: '', native: '', group: 'other' },
	{ english: 'Saurashtra/Sourashtra', native: '', group: 'other' },
	{ english: 'Savara', native: '', group: 'other' },
	{ english: 'Savi', native: '', group: 'other' },
	{ english: 'Sawai', native: '', group: 'other' },
	{ english: 'Scots/Ulster Scots/Hiberno-Scots/Ullans', native: '', group: 'other' },
	{ english: 'Scots Gaelic/Scottish Gaelic/Gaidhlig/Gaelic', native: '', group: 'other' },
	{ english: 'Selkup/Ostyak Samoyed', native: '', group: 'other' },
	{ english: 'Semnani', native: '', group: 'other' },
	{ english: 'Senaya', native: '', group: 'other' },
	{ english: 'Serbian', native: '', group: 'other' },
	{ english: 'Serbo-Croatian', native: '', group: 'other' },
	{ english: 'Sesotho', native: '', group: 'other' },
	{ english: 'Seto/Setu', native: '', group: 'other' },
	{ english: 'Seychellois Creole', native: '', group: 'other' },
	{ english: 'Shimaore', native: '', group: 'other' },
	{ english: 'Shina', native: '', group: 'other' },
	{ english: 'Shona', native: '', group: 'other' },
	{ english: 'Shor', native: '', group: 'other' },
	{ english: 'Shoshoni', native: '', group: 'other' },
	{ english: 'Shughni', native: '', group: 'other' },
	{ english: 'Shumashti', native: '', group: 'other' },
	{ english: 'Shuswap', native: '', group: 'other' },
	{ english: 'Sicilian', native: '', group: 'other' },
	{ english: 'Sidamo', native: '', group: 'other' },
	{ english: 'Sika', native: '', group: 'other' },
	{ english: 'Silesian', native: '', group: 'other' },
	{ english: "Silt'e/Selti/East Gurage", native: '', group: 'other' },
	{ english: 'Sindhi', native: '', group: 'other' },
	{ english: 'Sinhalese', native: '', group: 'other' },
	{ english: 'Sioux', native: '', group: 'other' },
	{ english: 'Sivandi', native: '', group: 'other' },
	{ english: 'Skolt Sami', native: '', group: 'other' },
	{ english: 'Slavey', native: '', group: 'other' },
	{ english: 'Slovak', native: '', group: 'other' },
	{ english: 'Slovene/Slovenian', native: '', group: 'other' },
	{ english: 'Soddo/Kistane', native: '', group: 'other' },
	{ english: 'Somali', native: '', group: 'other' },
	{ english: 'Sonjo/Temi', native: '', group: 'other' },
	{ english: 'Sonsorolese/Sonsorol', native: '', group: 'other' },
	{ english: 'Soqotri', native: '', group: 'other' },
	{ english: 'Sora', native: '', group: 'other' },
	{ english: 'Sorbian, Lower', native: '', group: 'other' },
	{ english: 'Sorbian, Upper', native: '', group: 'other' },
	{ english: 'Sourashtra', native: '', group: 'other' },
	{ english: 'Southern Sami', native: '', group: 'other' },
	{ english: 'South Estonian', native: '', group: 'other' },
	{ english: 'Southern Yukaghir/Tundra Yukaghir', native: '', group: 'other' },
	{ english: 'Sranan Tongo', native: '', group: 'other' },
	{ english: "St'at'imcets/Lillooet", native: '', group: 'other' },
	{ english: 'Sucite/Sìcìté Sénoufo', native: '', group: 'other' },
	{ english: 'Suba', native: '', group: 'other' },
	{ english: 'Sundanese', native: '', group: 'other' },
	{ english: 'Supyire/Supyire Senoufo', native: '', group: 'other' },
	{ english: 'Surigaonon', native: '', group: 'other' },
	{ english: 'Susu', native: '', group: 'other' },
	{ english: 'Svan', native: '', group: 'other' },
	{ english: 'Swati/Swazi/Siswati/Seswati', native: '', group: 'other' },
	{ english: 'Swedish', native: '', group: 'other' },
	{ english: 'Syriac', native: '', group: 'other' },

	{ english: 'Tabasaran/Tabassaran', native: '', group: 'other' },
	{ english: 'Tachelhit', native: '', group: 'other' },
	{ english: 'Tagalog', native: '', group: 'other' },
	{ english: 'Tahitian', native: '', group: 'other' },
	{ english: 'Tajik', native: '', group: 'other' },
	{ english: 'Takestani', native: '', group: 'other' },
	{ english: 'Talysh', native: '', group: 'other' },
	{ english: 'Tanacross', native: '', group: 'other' },
	{ english: 'Tangut', native: '', group: 'other' },
	{ english: 'Tarifit/Rifi/Riff Berber', native: '', group: 'other' },
	{ english: 'Tat/Tati', native: '', group: 'other' },
	{ english: 'Tatar', native: '', group: 'other' },
	{ english: 'Tausug', native: '', group: 'other' },
	{ english: 'Tehuelche', native: '', group: 'other' },
	{ english: 'Tetum', native: '', group: 'other' },
	{ english: 'Tepehua language', native: '', group: 'other' },
	{ english: 'Tepehuán language', native: '', group: 'other' },
	{ english: 'Tharu', native: '', group: 'other' },
	{ english: 'Tibetan', native: '', group: 'other' },
	{ english: 'Tigre/Xasa', native: '', group: 'other' },
	{ english: 'Tigrinya', native: '', group: 'other' },
	{ english: 'Timbisha/Panamint', native: '', group: 'other' },
	{ english: 'Tiv', native: '', group: 'other' },
	{ english: 'Tlingit', native: '', group: 'other' },
	{ english: 'Tobian', native: '', group: 'other' },
	{ english: 'Toda', native: '', group: 'other' },
	{ english: 'Tok Pisin', native: '', group: 'other' },
	{ english: 'Tokelauan', native: '', group: 'other' },
	{ english: 'Tonga', native: '', group: 'other' },
	{ english: 'Tongan', native: '', group: 'other' },
	{ english: 'Torwali/Turvali', native: '', group: 'other' },
	{ english: 'Tregami', native: '', group: 'other' },
	{ english: 'Tsat', native: '', group: 'other' },
	{ english: 'Tsez/Dido', native: '', group: 'other' },
	{ english: 'Tshiluba/Luba-Kasai/Luba-Lulua', native: '', group: 'other' },
	{ english: 'Tsonga', native: '', group: 'other' },
	{ english: 'Tswana/Setswana', native: '', group: 'other' },
	{ english: 'Tu/Monguor', native: '', group: 'other' },
	{ english: 'Tuareg languages/Tamasheq', native: '', group: 'other' },
	{ english: 'Tulu', native: '', group: 'other' },
	{ english: 'Tumbuka', native: '', group: 'other' },
	{ english: 'Tupiniquim', native: '', group: 'other' },
	{ english: 'Turkmen', native: '', group: 'other' },
	{ english: 'Turoyo', native: '', group: 'other' },
	{ english: 'Tuvaluan', native: '', group: 'other' },
	{ english: 'Tuvan Tuvin/Tyvan', native: '', group: 'other' },

	{ english: 'Udihe/Ude/Udege', native: '', group: 'other' },
	{ english: 'Udmurt/Votyak', native: '', group: 'other' },
	{ english: 'Ukrainian', native: '', group: 'other' },
	{ english: 'Ukwuani-Aboh-Ndoni', native: '', group: 'other' },
	{ english: 'Ulch/Olcha', native: '', group: 'other' },
	{ english: 'Unserdeutsch/Rabaul Creole German', native: '', group: 'other' },
	{ english: 'Upper Sorbian', native: '', group: 'other' },
	{ english: 'Uripiv', native: '', group: 'other' },
	{ english: 'Urum', native: '', group: 'other' },
	{ english: 'Ute', native: '', group: 'other' },
	{ english: 'Uyghur/Uigur', native: '', group: 'other' },
	{ english: 'Uzbek', native: '', group: 'other' },

	{ english: 'Vafsi', native: '', group: 'other' },
	{ english: 'Valencian', native: '', group: 'other' },
	{ english: 'Vasi-vari/Prasuni', native: '', group: 'other' },
	{ english: 'Venda/Tshivenda', native: '', group: 'other' },
	{ english: 'Venetian', native: '', group: 'other' },
	{ english: 'Veps', native: '', group: 'other' },
	{ english: 'Võro', native: '', group: 'other' },
	{ english: 'Votic/Votian', native: '', group: 'other' },

	{ english: 'Waddar', native: '', group: 'other' },
	{ english: 'Waigali/Kalasha-Ala', native: '', group: 'other' },
	{ english: 'Waima/Roro', native: '', group: 'other' },
	{ english: 'Wakhi', native: '', group: 'other' },
	{ english: 'Walloon', native: '', group: 'other' },
	{ english: 'Waray-Waray/Binisaya', native: '', group: 'other' },
	{ english: 'Washo', native: '', group: 'other' },
	{ english: 'Welsh', native: '', group: 'other' },
	{ english: 'Western Neo-Aramaic', native: '', group: 'other' },
	{ english: 'Wolane', native: '', group: 'other' },
	{ english: 'Wolof', native: '', group: 'other' },

	{ english: 'Xhosa', native: '', group: 'other' },
	{ english: 'Xiang', native: '', group: 'other' },
	{ english: 'Xibe/Sibo', native: '', group: 'other' },
	{ english: 'Xipaya', native: '', group: 'other' },
	{ english: 'Xóõ', native: '', group: 'other' },

	{ english: 'Yaaku language', native: '', group: 'other' },
	{ english: 'Yaeyama language', native: '', group: 'other' },
	{ english: 'Yaghnobi', native: '', group: 'other' },
	{ english: 'Yakut', native: '', group: 'other' },
	{ english: 'Yankunytjatjara language', native: '', group: 'other' },
	{ english: 'Yanomami', native: '', group: 'other' },
	{ english: 'Yanyuwa', native: '', group: 'other' },
	{ english: 'Yapese', native: '', group: 'other' },
	{ english: 'Yaqui', native: '', group: 'other' },
	{ english: 'Yauma', native: '', group: 'other' },
	{ english: 'Yavapai', native: '', group: 'other' },
	{ english: 'Yazdi', native: '', group: 'other' },
	{ english: 'Yazgulyam/Yazgulami', native: '', group: 'other' },
	{ english: 'Yemenite Hebrew', native: '', group: 'other' },
	{ english: 'Yeni language', native: '', group: 'other' },
	{ english: 'Yevanic language', native: '', group: 'other' },
	{ english: 'Yi language', native: '', group: 'other' },
	{ english: 'Yiddish', native: '', group: 'other' },
	{ english: 'Yidgha', native: '', group: 'other' },
	{ english: 'Yogur', native: '', group: 'other' },
	{ english: 'Yokutsan languages', native: '', group: 'other' },
	{ english: 'Yonaguni language', native: '', group: 'other' },
	{ english: 'Yoruba language', native: '', group: 'other' },
	{ english: 'Yucatec Maya language', native: '', group: 'other' },
	{ english: 'Yuchi language', native: '', group: 'other' },
	{ english: 'Yugur', native: '', group: 'other' },
	{ english: 'Yukaghir languages', native: '', group: 'other' },
	{ english: 'Yupik language', native: '', group: 'other' },
	{ english: 'Yurats language', native: '', group: 'other' },
	{ english: 'Yurok language', native: '', group: 'other' },

	{ english: 'Záparo', native: '', group: 'other' },
	{ english: 'Zapotec', native: '', group: 'other' },
	{ english: 'Zazaki', native: '', group: 'other' },
	{ english: 'Zulu', native: '', group: 'other' },
	{ english: 'Zuñi/Zuni', native: '', group: 'other' },
	{ english: 'Zway/Zay', native: '', group: 'other' },
];
