export type Language = {
	english: string;
	native: string;
};

export const Languages = [
	{ english: 'Ancient Meitei', native: '' },
	{ english: "'Are'are", native: '' },
	{ english: "'Auhelawa", native: '' },
	{ english: "A'Tong", native: '' },
	{ english: 'Aari', native: '' },
	{ english: 'Abanyom', native: '' },
	{ english: 'Abaza', native: '' },
	{ english: 'Abkhaz/Abkhazian', native: '' },
	{ english: 'Abujmaria', native: '' },
	{ english: 'Acehnese', native: '' },
	{ english: 'Adamorobe Sign Language', native: '' },
	{ english: 'Adele', native: '' },
	{ english: 'Adyghe', native: '' },
	{ english: 'Afar', native: '' },
	{ english: 'Afrikaans', native: '' },
	{ english: 'Afro-Seminole Creole', native: '' },
	{ english: 'Aimaq/Barbari', native: '' },
	{ english: 'Aini', native: '' },
	{ english: 'Ainu', native: '' },
	{ english: 'Akan', native: '' },
	{ english: 'Akawaio', native: '' },
	{ english: 'Aklanon', native: '' },
	{ english: 'Albanian', native: '' },
	{ english: 'Aleut', native: '' },
	{ english: 'Algonquin', native: '' },
	{ english: 'Alsatian', native: '' },
	{ english: 'Altay', native: '' },
	{ english: 'Alutor', native: '' },
	{ english: 'American Sign Language', native: '' },
	{ english: 'Amharic', native: '' },
	{ english: 'Anda', native: '' },
	{ english: 'Amdang', native: '' },
	{ english: 'Angika', native: '' },
	{ english: 'Anyin', native: '' },
	{ english: 'Ao', native: '' },
	{ english: 'A-Pucikwar', native: '' },
	{ english: 'Arabic', native: '' },
	{ english: 'Aragonese', native: '' },
	{ english: 'Aramaic', native: '' },
	{ english: 'Are', native: '' },
	{ english: 'Argobba', native: '' },
	{ english: 'Aromanian/Macedo-Romanian', native: '' },
	{ english: 'Armenian', native: '' },
	{ english: 'Arvanitic', native: '' },
	{ english: 'Ashkun', native: '' },
	{ english: 'Assamese', native: '' },
	{ english: 'Assyrian Neo-Aramaic', native: '' },
	{ english: 'Ateso/Teso', native: '' },
	{ english: 'Asi', native: '' },
	{ english: 'Asturian', native: '' },
	{ english: 'Auslan', native: '' },
	{ english: 'Austro-Bavarian', native: '' },
	{ english: 'Avar', native: '' },
	{ english: 'Avestan', native: '' },
	{ english: 'Awadhi', native: '' },
	{ english: 'Aymara', native: '' },
	{ english: 'Azerbaijani', native: '' },
	{ english: 'Badaga', native: '' },
	{ english: 'Badeshi', native: '' },
	{ english: 'Bahnar', native: '' },
	{ english: 'Balinese', native: '' },
	{ english: 'Balochi', native: '' },
	{ english: 'Balti', native: '' },
	{ english: 'Bambara/Bamanankan', native: '' },
	{ english: 'Banjar', native: '' },
	{ english: 'Banyumasan', native: '' },
	{ english: 'Bartangi', native: '' },
	{ english: 'Basaa', native: '' },
	{ english: 'Bashkardi', native: '' },
	{ english: 'Bashkir', native: '' },
	{ english: 'Basque', native: '' },
	{ english: 'Batak Karo', native: '' },
	{ english: 'Batak Toba', native: '' },
	{ english: 'Bats', native: '' },
	{ english: 'Beja', native: '' },
	{ english: 'Belarusian', native: '' },
	{ english: 'Belhare', native: '' },
	{ english: 'Berta', native: '' },
	{ english: 'Bemba', native: '' },
	{ english: 'Bengali', native: '' },
	{ english: 'Bezhta', native: '' },
	{ english: 'Betawi', native: '' },
	{ english: 'Bete', native: '' },
	{ english: 'Bhili', native: '' },
	{ english: 'Bhojpuri', native: '' },
	{ english: 'Bijil Neo-Aramaic', native: '' },
	{ english: 'Bikol', native: '' },
	{ english: 'Bikya/Furu', native: '' },
	{ english: 'Bissa', native: '' },
	{ english: 'Blackfoot', native: '' },
	{ english: 'Boholano', native: '' },
	{ english: 'Bohtan Neo-Aramaic', native: '' },
	{ english: 'Bonan/Paoan', native: '' },
	{ english: 'Bororo', native: '' },
	{ english: 'Bodo', native: '' },
	{ english: 'Bosnian', native: '' },
	{ english: 'Brahui', native: '' },
	{ english: 'Breton', native: '' },
	{ english: 'British Sign Language', native: '' },
	{ english: 'Bua', native: '' },
	{ english: 'Buginese', native: '' },
	{ english: 'Bukusu', native: '' },
	{ english: 'Bulgarian', native: '' },
	{ english: 'Bunjevac', native: '' },
	{ english: 'Burmese', native: '' },
	{ english: 'Burushaski', native: '' },
	{ english: 'Buryat', native: '' },
	{ english: 'Caddo', native: '' },
	{ english: 'Cahuilla', native: '' },
	{ english: 'Caluyanon/Caluyanun', native: '' },
	{ english: 'Cantonese', native: '' },
	{ english: 'Catalan', native: '' },
	{ english: 'Cayuga', native: '' },
	{ english: 'Cebuano', native: '' },
	{ english: 'Chabacano/Chavacano', native: '' },
	{ english: 'Chaga/Kichagga', native: '' },
	{ english: 'Chakma', native: '' },
	{ english: 'Chaldean Neo-Aramaic', native: '' },
	{ english: 'Chamorro', native: '' },
	{ english: 'Chaouia/Tachawit', native: '' },
	{ english: 'Chechen', native: '' },
	{ english: 'Chenchu', native: '' },
	{ english: 'Chenoua', native: '' },
	{ english: 'Cherokee', native: '' },
	{ english: 'Cheyenne', native: '' },
	{ english: 'Chhattisgarhi', native: '' },
	{ english: 'Chickasaw', native: '' },
	{ english: 'Chintang/Chhintang', native: '' },
	{ english: 'Chilcotin', native: '' },
	{ english: 'Chinese', native: '' },
	{ english: 'Chiricahua/Mescalero-Chiricahua Apache', native: '' },
	{ english: 'Chichewa/Nyanja', native: '' },
	{ english: 'Chipewyan', native: '' },
	{ english: 'Chittagonian', native: '' },
	{ english: 'Choctaw', native: '' },
	{ english: 'Chorasmian/Khwarezmian', native: '' },
	{ english: 'Chukchi/Chukot', native: '' },
	{ english: 'Chulym', native: '' },
	{ english: 'Church Slavonic', native: '' },
	{ english: 'Chuukese/Trukese', native: '' },
	{ english: 'Chuvash', native: '' },
	{ english: 'Cocoma/Cocama', native: '' },
	{ english: 'Cocopa', native: '' },
	{ english: "Coeur d'Alene", native: '' },
	{ english: 'Comanche', native: '' },
	{ english: 'Comorian', native: '' },
	{ english: 'Cornish', native: '' },
	{ english: 'Corsican', native: '' },
	{ english: 'Cree', native: '' },
	{ english: 'Crimean Tatar/Crimean Turkish', native: '' },
	{ english: 'Croatian', native: '' },
	{ english: 'Cuyonon', native: '' },
	{ english: 'Czech', native: '' },

	{ english: 'Dagbani', native: '' },
	{ english: 'Dahlik', native: '' },
	{ english: 'Dalecarlian', native: '' },
	{ english: 'Dameli', native: '' },
	{ english: 'Danish', native: '' },
	{ english: 'Dargin', native: '' },
	{ english: 'Dakota', native: '' },
	{ english: 'Dari', native: '' },
	{ english: 'Dari-Persian', native: '' },
	{ english: 'Daur/Dagur', native: '' },
	{ english: "Dena'ina/Tanaina", native: '' },
	{ english: 'Dhatki', native: '' },
	{ english: 'Dhivehi/Maldivian', native: '' },
	{ english: 'Dida', native: '' },
	{ english: 'Dioula/Jula', native: '' },
	{ english: 'Dogri', native: '' },
	{ english: 'Dogrib/Tli Cho', native: '' },
	{ english: 'Dolgan', native: '' },
	{ english: 'Domaaki/Dumaki', native: '' },
	{ english: 'Dongxiang/Santa', native: '' },
	{ english: 'Duala', native: '' },
	{ english: 'Dungan', native: '' },
	{ english: 'Dutch', native: '' },
	{ english: 'Dzhidi/Judeo-Persian', native: '' },
	{ english: 'Dzongkha', native: '' },

	{ english: 'Eastern Yugur', native: '' },
	{ english: 'Edo', native: '' },
	{ english: 'Efik', native: '' },
	{ english: 'Esan', native: '' },
	{ english: 'Egyptian Arabic', native: '' },
	{ english: 'Ekoti', native: '' },
	{ english: 'Enets/Yenisey Samoyed', native: '' },
	{ english: 'English', native: '' },
	{ english: 'Erzya', native: '' },
	{ english: 'Esperanto', native: '' },
	{ english: 'Estonian', native: '' },
	{ english: 'Even', native: '' },
	{ english: 'Evenk/Evenki', native: '' },
	{ english: 'Ewe', native: '' },
	{ english: 'Extremaduran', native: '' },

	{ english: 'Faroese language', native: '' },
	{ english: 'Fang', native: '' },
	{ english: 'Fijian', native: '' },
	{ english: 'Filipino', native: '' },
	{ english: 'Finnish', native: '' },
	{ english: 'Finnish Sign Language', native: '' },
	{ english: 'Flemish language', native: '' },
	{ english: 'Fon', native: '' },
	{ english: 'Franco-Provençal/Arpitan', native: '' },
	{ english: 'French', native: '' },
	{ english: 'French Sign Language', native: '' },
	{ english: 'Frisian, North', native: '' },
	{ english: 'Frisian, Saterland', native: '' },
	{ english: 'Frisian, West', native: '' },
	{ english: 'Friulian', native: '' },
	{ english: 'Fula/Fulfulde/Fulani', native: '' },
	{ english: 'Fur', native: '' },

	{ english: 'Ga', native: '' },
	{ english: 'Gadaba', native: '' },
	{ english: 'Gagauz', native: '' },
	{ english: 'Galician', native: '' },
	{ english: 'Gallo', native: '' },
	{ english: 'Gan', native: '' },
	{ english: 'Ganda', native: '' },
	{ english: 'Gangte', native: '' },
	{ english: 'Garhwali', native: '' },
	{ english: 'Gayo', native: '' },
	{ english: 'Gen/Gẽ/Mina', native: '' },
	{ english: 'Georgian', native: '' },
	{ english: 'German', native: '' },
	{ english: 'German Sign Language', native: '' },
	{ english: 'Gikuyu/Kikuyu', native: '' },
	{ english: 'Gilbertese/Kiribati', native: '' },
	{ english: 'Gileki', native: '' },
	{ english: 'Goaria', native: '' },
	{ english: 'Gondi', native: '' },
	{ english: 'Gorani/Gurani', native: '' },
	{ english: 'Gowro', native: '' },
	{ english: 'Gawar-Bati/Gowari/Narsati', native: '' },
	{ english: 'Greek', native: '' },
	{ english: 'Guaraní', native: '' },
	{ english: 'Guinea-Bissau Creole', native: '' },
	{ english: 'Gujarati', native: '' },
	{ english: 'Gula Iro/Kulaal', native: '' },
	{ english: 'Gullah/Sea Island Creole English', native: '' },
	{ english: 'Gusii', native: '' },
	{ english: "Gwich'in", native: '' },

	{ english: 'Hadza', native: '' },
	{ english: 'Haida', native: '' },
	{ english: 'Haitian Creole', native: '' },
	{ english: 'Hakka', native: '' },
	{ english: 'Hän', native: '' },
	{ english: 'Harari', native: '' },
	{ english: 'Harauti', native: '' },
	{ english: 'Harsusi', native: '' },
	{ english: 'Haryanavi', native: '' },
	{ english: 'Harzani', native: '' },
	{ english: 'Hausa', native: '' },
	{ english: 'Havasupai/Upland Yuman', native: '' },
	{ english: 'Hawaiian', native: '' },
	{ english: 'Hawaii Pidgin Sign Language', native: '' },
	{ english: 'Hazaragi', native: '' },
	{ english: 'Hebrew', native: '' },
	{ english: 'Herero', native: '' },
	{ english: 'Hértevin', native: '' },
	{ english: 'Hiligaynon', native: '' },
	{ english: 'Hindi', native: '' },
	{ english: 'Hinukh', native: '' },
	{ english: 'Hiri Motu', native: '' },
	{ english: 'Hixkaryana', native: '' },
	{ english: 'Hmong', native: '' },
	{ english: 'Ho', native: '' },
	{ english: 'Hobyót', native: '' },
	{ english: 'Hopi', native: '' },
	{ english: 'Hulaulá', native: '' },
	{ english: 'Hungarian', native: '' },
	{ english: 'Hunsrik', native: '' },
	{ english: 'Hutterite German', native: '' },

	{ english: 'Ibibio', native: '' },
	{ english: 'Iban', native: '' },
	{ english: 'Ibanag', native: '' },
	{ english: 'Icelandic', native: '' },
	{ english: 'Ido', native: '' },
	{ english: 'Ifè', native: '' },
	{ english: 'Igbo/Ibo/Biafra', native: '' },
	{ english: 'Ikalanga/Kalanga', native: '' },
	{ english: 'Ili Turki', native: '' },
	{ english: 'Ilokano/Ilocano', native: '' },
	{ english: 'Inari Sami', native: '' },
	{ english: 'Indonesian', native: '' },
	{ english: 'Ingrian/Izhorian', native: '' },
	{ english: 'Ingush', native: '' },
	{ english: 'Interlingua', native: '' },
	{ english: 'Inuktitut', native: '' },
	{ english: 'Inupiaq', native: '' },
	{ english: 'Inuvialuktun', native: '' },
	{ english: 'Iraqw', native: '' },
	{ english: 'Irish/Irish Gaelic', native: '' },
	{ english: 'Irish Sign Language', native: '' },
	{ english: 'Irula', native: '' },
	{ english: 'Isan/Northeastern Thai', native: '' },
	{ english: 'Ishkashimi/Ishkashmi', native: '' },
	{ english: 'Istro-Romanian', native: '' },
	{ english: 'Italian', native: '' },
	{ english: 'Itelmen/Kamchadal', native: '' },

	{ english: 'Jacaltec/Jakalteko', native: '' },
	{ english: 'Jalaa', native: '' },
	{ english: 'Japanese', native: '' },
	{ english: 'Jaqaru', native: '' },
	{ english: 'Jarai', native: '' },
	{ english: 'Javanese', native: '' },
	{ english: 'Jibbali/Shehri', native: '' },
	{ english: 'Jewish Babylonian Aramaic', native: '' },
	{ english: 'Jicarilla Apache', native: '' },
	{ english: 'Juang', native: '' },
	{ english: 'Jurchen', native: '' },

	{ english: 'Kabardian', native: '' },
	{ english: 'Kabyle', native: '' },
	{ english: 'Kachin/Jingpo', native: '' },
	{ english: 'Kalaallisut/Greenlandic', native: '' },
	{ english: 'Kalami/Gawri/Dirwali', native: '' },
	{ english: 'Kalasha', native: '' },
	{ english: 'Kalmyk/Oirat', native: '' },
	{ english: 'Kalto/Nahali', native: '' },
	{ english: 'Kankanai/Kankanaey', native: '' },
	{ english: 'Kannada', native: '' },
	{ english: 'Kaonde/Chikaonde', native: '' },
	{ english: 'Kapampangan', native: '' },
	{ english: 'Karachay-Balkar', native: '' },
	{ english: 'Karagas', native: '' },
	{ english: 'Karaim', native: '' },
	{ english: 'Karakalpak', native: '' },
	{ english: 'Karelian', native: '' },
	{ english: 'Kashmiri', native: '' },
	{ english: 'Kashubian', native: '' },
	{ english: 'Kazakh', native: '' },
	{ english: 'Kerek', native: '' },
	{ english: 'Ket', native: '' },
	{ english: 'Khakas', native: '' },
	{ english: 'Khalaj', native: '' },
	{ english: 'Kham/Sheshi', native: '' },
	{ english: 'Khandeshi', native: '' },
	{ english: 'Khanty/Ostyak', native: '' },
	{ english: 'Khasi', native: '' },
	{ english: 'Khitan', native: '' },
	{ english: 'Khmer', native: '' },
	{ english: 'Khmu', native: '' },
	{ english: 'Khowar', native: '' },
	{ english: 'Kildin Sami', native: '' },
	{ english: 'Kimatuumbi', native: '' },
	{ english: 'Kinaray-a/Hiraya', native: '' },
	{ english: 'Kinyarwanda', native: '' },
	{ english: 'Kirombo', native: '' },
	{ english: 'Kirundi', native: '' },
	{ english: 'Kivunjo', native: '' },
	{ english: 'Klallam/Clallam', native: '' },
	{ english: 'Kodava Takk/Kodagu/Coorgi', native: '' },
	{ english: 'Kohistani/Khili', native: '' },
	{ english: 'Kolami', native: '' },
	{ english: 'Komi/Komi-Zyrian', native: '' },
	{ english: 'Konkani', native: '' },
	{ english: 'Kongo/Kikongo', native: '' },
	{ english: 'Koraga', native: '' },
	{ english: 'Korandje', native: '' },
	{ english: 'Korean', native: '' },
	{ english: 'Korku', native: '' },
	{ english: 'Korowai', native: '' },
	{ english: 'Korwa', native: '' },
	{ english: 'Koryak', native: '' },
	{ english: 'Kosraean', native: '' },
	{ english: 'Kota', native: '' },
	{ english: 'Koyra Chiini/Western Songhay', native: '' },
	{ english: 'Koy Sanjaq Surat', native: '' },
	{ english: 'Koya', native: '' },
	{ english: 'Krymchak/Judeo-Crimean Tatar', native: '' },
	{ english: 'Kujarge', native: '' },
	{ english: 'Kui', native: '' },
	{ english: 'Kumauni', native: '' },
	{ english: 'Kumyk', native: '' },
	{ english: 'Kumzari', native: '' },
	{ english: '!Kung', native: '' },
	{ english: 'Kurdish', native: '' },
	{ english: 'Kurukh/Kurux', native: '' },
	{ english: 'Kusunda', native: '' },
	{ english: 'Kutenai/Kootenay/Ktunaxa', native: '' },
	{ english: 'Kwanyama/Ovambo', native: '' },
	{ english: 'Kxoe', native: '' },
	{ english: 'Kyrgyz/Kirghiz', native: '' },

	{ english: 'Laal', native: '' },
	{ english: 'Ladakhi', native: '' },
	{ english: 'Ladin', native: '' },
	{ english: 'Ladino/Judeo-Spanish', native: '' },
	{ english: 'Laki', native: '' },
	{ english: 'Lakota/Lakhota/Teton', native: '' },
	{ english: 'Lambadi/Lamani/Banjari', native: '' },
	{ english: 'Lao/Laotian', native: '' },
	{ english: 'Larestani', native: '' },
	{ english: 'Latin', native: '' },
	{ english: 'Latvian', native: '' },
	{ english: 'Laz/Lazuri', native: '' },
	{ english: 'Leonese', native: '' },
	{ english: 'Lepcha', native: '' },
	{ english: 'Lezgi/Agul', native: '' },
	{ english: 'Ligbi/Ligby', native: '' },
	{ english: 'Limbu', native: '' },
	{ english: 'Limburgish', native: '' },
	{ english: 'Lingala', native: '' },
	{ english: 'Lipan Apache', native: '' },
	{ english: 'Lisan al-Dawat', native: '' },
	{ english: 'Lishana Deni', native: '' },
	{ english: 'Lishanid Noshan/Lishana Didan', native: '' },
	{ english: 'Lithuanian', native: '' },
	{ english: 'Livonian language/Liv', native: '' },
	{ english: 'Lombard', native: '' },
	{ english: 'Lotha', native: '' },
	{ english: 'Low German/Low Saxon', native: '' },
	{ english: 'Lower Sorbian', native: '' },
	{ english: 'Lozi/Silozi', native: '' },
	{ english: 'Ludic/Ludian', native: '' },
	{ english: 'Lunda/Chilunda', native: '' },
	{ english: 'Luo', native: '' },
	{ english: 'Luri', native: '' },
	{ english: 'Lushootseed', native: '' },
	{ english: 'Lusoga/Soga', native: '' },
	{ english: 'Luvale', native: '' },
	{ english: 'Luwati', native: '' },
	{ english: 'Luxembourgish', native: '' },
	{ english: 'Lycian', native: '' },
	{ english: 'Lydian', native: '' },

	{ english: 'Macedonian', native: '' },
	{ english: 'Magadhi', native: '' },
	{ english: 'Maguindanao', native: '' },
	{ english: 'Maithili', native: '' },
	{ english: 'Makasar', native: '' },
	{ english: 'Makhuwa/Makua', native: '' },
	{ english: 'Makhuwa-Meetto', native: '' },
	{ english: 'Malagasy', native: '' },
	{ english: 'Malay', native: '' },
	{ english: 'Malayalam', native: '' },
	{ english: 'Malaysian Sign Language', native: '' },
	{ english: 'Maltese', native: '' },
	{ english: 'Malto/Sauria Paharia', native: '' },
	{ english: 'Malvi/Malavi/Ujjaini', native: '' },
	{ english: 'Mam', native: '' },
	{ english: 'Manchu', native: '' },
	{ english: 'Mandaic', native: '' },
	{ english: 'Mandarin', native: '' },
	{ english: 'Mandinka', native: '' },
	{ english: 'Mansi/Vogul', native: '' },
	{ english: 'Manx', native: '' },
	{ english: 'Manyika', native: '' },
	{ english: 'Maori', native: '' },
	{ english: 'Mapudungun/Mapuche', native: '' },
	{ english: 'Maranao', native: '' },
	{ english: 'Marathi', native: '' },
	{ english: 'Mari/Cheremis', native: '' },
	{ english: 'Maria', native: '' },
	{ english: 'Marquesan', native: '' },
	{ english: 'Marshallese/Ebon', native: '' },
	{ english: "Martha's Vineyard Sign Language", native: '' },
	{ english: 'Masaba', native: '' },
	{ english: 'Masbatenyo/Minasbate (Malayo-Polynesian', native: '' },
	{ english: 'Meitei/Manipuri/Meithei', native: '' },
	{ english: 'Mauritian Creole/Morisyen', native: '' },
	{ english: 'Maya', native: '' },
	{ english: 'Mazandarani/Tabari(Iranian)', native: '' },
	{ english: 'Meänkieli/Tornedalen Finnish', native: '' },
	{ english: 'Megleno-Romanian', native: '' },
	{ english: 'Megrelian/Mingrelian', native: '' },
	{ english: 'Mehri/Mahri', native: '' },
	{ english: 'Menominee', native: '' },
	{ english: 'Mentawai', native: '' },
	{ english: 'Meroitic', native: '' },
	{ english: 'Mescalero Apache', native: '' },
	{ english: 'Meru/Kimeru', native: '' },
	{ english: 'Michif', native: '' },
	{ english: 'Mikasuki/Miccosukee', native: '' },
	{ english: "Mi'kmaq/Micmac", native: '' },
	{ english: 'Minangkabau', native: '' },
	{ english: 'Mirandese', native: '' },
	{ english: 'Mobilian Jargon', native: '' },
	{ english: 'Moghol', native: '' },
	{ english: 'Mohawk', native: '' },
	{ english: 'Moksha', native: '' },
	{ english: 'Molengue', native: '' },
	{ english: 'Mon', native: '' },
	{ english: 'Mongolian', native: '' },
	{ english: 'Mono', native: '' },
	{ english: 'Mono', native: '' },
	{ english: 'Mono', native: '' },
	{ english: 'Montagnais', native: '' },
	{ english: 'Montenegrin', native: '' },
	{ english: 'Motu', native: '' },
	{ english: 'Muher', native: '' },
	{ english: 'Mundari', native: '' },
	{ english: 'Munji', native: '' },
	{ english: 'Muria', native: '' },
	{ english: 'Template:Mwaghavul Template:Myene', native: '' },
	{ english: '', native: '' },

	{ english: 'Nafaanra', native: '' },
	{ english: 'Nagarchal', native: '' },
	{ english: 'Nahuatl', native: '' },
	{ english: 'Nama', native: '' },
	{ english: 'Nanai', native: '' },
	{ english: 'Nauruan', native: '' },
	{ english: 'Navajo/Navaho', native: '' },
	{ english: 'Ndau/Southeast Shona', native: '' },
	{ english: 'Ndebele', native: '' },
	{ english: 'Ndonga', native: '' },
	{ english: 'Neapolitan', native: '' },
	{ english: 'Negidal', native: '' },
	{ english: 'Nepal Bhasa/Newari', native: '' },
	{ english: 'Nepali', native: '' },
	{ english: 'New Zealand Sign Language', native: '' },
	{ english: 'Nihali/Nahali', native: '' },
	{ english: 'Nganasan/Tavgi', native: '' },
	{ english: 'Ngumba', native: '' },
	{ english: 'Nheengatu/Geral/Modern Tupí', native: '' },
	{ english: 'Nias', native: '' },
	{ english: 'Nicaraguan Sign Language', native: '' },
	{ english: 'Niellim', native: '' },
	{ english: 'Nigerian Pidgin', native: '' },
	{ english: 'Nisenan', native: '' },
	{ english: 'Niuean/Niue', native: '' },
	{ english: 'Nivkh/Gilyak', native: '' },
	{ english: 'Nogai', native: '' },
	{ english: 'Norfuk/Norfolk/Pitcairn-Norfolk', native: '' },
	{ english: 'Norman/Norman-French', native: '' },
	{ english: 'Northern Sami', native: '' },
	{ english: 'Northern Sotho/Sepedi', native: '' },
	{ english: 'Northern Straits Salish)', native: '' },
	{ english: 'Northern Yukaghir', native: '' },
	{ english: 'Norwegian', native: '' },
	{ english: 'Nuer', native: '' },
	{ english: 'Nuxálk/Bella Coola', native: '' },
	{ english: 'Nyabwa', native: '' },
	{ english: 'Nyah Kur', native: '' },
	{ english: 'Nyangumarta', native: '' },
	{ english: 'Nyoro', native: '' },
	{ english: 'Nǀu', native: '' },

	{ english: 'Occitan/Provençal', native: '' },
	{ english: 'Ojibwe/Ojibwa/Chippewa', native: '' },
	{ english: 'Okinawan', native: '' },
	{ english: 'Olonets Karelian/Liv/Livvi', native: '' },
	{ english: 'Omagua', native: '' },
	{ english: 'Ongota', native: '' },
	{ english: 'Odia', native: '' },
	{ english: 'Ormuri', native: '' },
	{ english: 'Oroch', native: '' },
	{ english: 'Orok', native: '' },
	{ english: 'Oromo/Afaan Oromoo', native: '' },
	{ english: 'Ossetic/Ossetian', native: '' },
	{ english: 'Old East Slavic/Old Russian', native: '' },
	{ english: 'Old Prussian', native: '' },

	{ english: 'Páez/Nasa Yuwe', native: '' },
	{ english: 'Palauan', native: '' },
	{ english: 'Pangasinan', native: '' },
	{ english: 'Papiamento/Papiamentu', native: '' },
	{ english: 'Parachi', native: '' },
	{ english: 'Parya', native: '' },
	{ english: 'Pashto/Pushto/Pashtu', native: '' },
	{ english: 'Pennsylvania Dutch/Pennsylvania German', native: '' },
	{ english: 'Persian/farsi, as it is referred to in the Persian language', native: '' },
	{ english: 'Phalura', native: '' },
	{ english: 'Phuthi', native: '' },
	{ english: 'Pig Latin', native: '' },
	{ english: 'Picard', native: '' },
	{ english: 'Pirahã', native: '' },
	{ english: 'Plautdietsch/Mennonite Low German', native: '' },
	{ english: 'Polish', native: '' },
	{ english: 'Portuguese', native: '' },
	{ english: 'Pothohari/Pahari-Potwari', native: '' },
	{ english: 'Pradhan/Pardhan', native: '' },
	{ english: 'Puelche', native: '' },
	{ english: 'Puma', native: '' },
	{ english: 'Punjabi/Panjabi/Gurmukhi', native: '' },

	{ english: 'Qashqai/Ghashghai', native: '' },
	{ english: 'Quebec Sign Language', native: '' },
	{ english: 'Quechua', native: '' },

	{ english: 'Rajasthani', native: '' },
	{ english: 'Ratagnon/Datagnon/Latagnun', native: '' },
	{ english: 'Réunion Creole/Bourbonnais', native: '' },
	{ english: 'Romanian', native: '' },
	{ english: 'Romansh/Rhaeto-Romance', native: '' },
	{ english: 'Romany', native: '' },
	{ english: 'Romblomanon', native: '' },
	{ english: 'Rotokas', native: '' },
	{ english: 'Runyankole language/Nyankore', native: '' },
	{ english: 'Russian', native: '' },
	{ english: 'Russian Sign Language', native: '' },
	{ english: 'Ruthenian/Rusyn/Carpathian', native: '' },

	{ english: 'Sadri', native: '' },
	{ english: 'Salar', native: '' },
	{ english: 'Samoan', native: '' },
	{ english: 'Sandawe', native: '' },
	{ english: 'Sango', native: '' },
	{ english: 'Sanskrit', native: '' },
	{ english: 'Santali', native: '' },
	{ english: 'Sara', native: '' },
	{ english: 'Saraiki/Seraiki/Siraiki', native: '' },
	{ english: 'Saramaccan', native: '' },
	{ english: 'Sardinian', native: '' },
	{ english: 'Sarikoli', native: '' },
	{ english: 'Standard Arabic', native: '' },
	{ english: '', native: '' },
	{ english: 'Saurashtra/Sourashtra', native: '' },
	{ english: 'Savara', native: '' },
	{ english: 'Savi', native: '' },
	{ english: 'Sawai', native: '' },
	{ english: 'Scots/Ulster Scots/Hiberno-Scots/Ullans', native: '' },
	{ english: 'Scots Gaelic/Scottish Gaelic/Gaidhlig/Gaelic', native: '' },
	{ english: 'Selangor Sign Language', native: '' },
	{ english: 'Selkup/Ostyak Samoyed', native: '' },
	{ english: 'Semnani', native: '' },
	{ english: 'Senaya', native: '' },
	{ english: 'Serbian', native: '' },
	{ english: 'Serbo-Croatian', native: '' },
	{ english: 'Sesotho', native: '' },
	{ english: 'Seto/Setu', native: '' },
	{ english: 'Seychellois Creole', native: '' },
	{ english: 'Shimaore', native: '' },
	{ english: 'Shina', native: '' },
	{ english: 'Shona', native: '' },
	{ english: 'Shor', native: '' },
	{ english: 'Shoshoni', native: '' },
	{ english: 'Shughni', native: '' },
	{ english: 'Shumashti', native: '' },
	{ english: 'Shuswap', native: '' },
	{ english: 'Sicilian', native: '' },
	{ english: 'Sidamo', native: '' },
	{ english: 'Sika', native: '' },
	{ english: 'Silesian', native: '' },
	{ english: "Silt'e/Selti/East Gurage", native: '' },
	{ english: 'Sindhi', native: '' },
	{ english: 'Sinhalese', native: '' },
	{ english: 'Sioux', native: '' },
	{ english: 'Sivandi', native: '' },
	{ english: 'Skolt Sami', native: '' },
	{ english: 'Slavey', native: '' },
	{ english: 'Slovak', native: '' },
	{ english: 'Slovene/Slovenian', native: '' },
	{ english: 'Soddo/Kistane', native: '' },
	{ english: 'Somali', native: '' },
	{ english: 'Sonjo/Temi', native: '' },
	{ english: 'Sonsorolese/Sonsorol', native: '' },
	{ english: 'Soqotri', native: '' },
	{ english: 'Sora', native: '' },
	{ english: 'Sorbian, Lower', native: '' },
	{ english: 'Sorbian, Upper', native: '' },
	{ english: 'Sourashtra', native: '' },
	{ english: 'Southern Sami', native: '' },
	{ english: 'South Estonian', native: '' },
	{ english: 'Southern Yukaghir/Tundra Yukaghir', native: '' },
	{ english: 'Spanish', native: '' },
	{ english: 'Sranan Tongo', native: '' },
	{ english: "St'at'imcets/Lillooet", native: '' },
	{ english: 'Sucite/Sìcìté Sénoufo', native: '' },
	{ english: 'Suba', native: '' },
	{ english: 'Sundanese', native: '' },
	{ english: 'Supyire/Supyire Senoufo', native: '' },
	{ english: 'Surigaonon', native: '' },
	{ english: 'Susu', native: '' },
	{ english: 'Svan', native: '' },
	{ english: 'Swahili', native: '' },
	{ english: 'Swati/Swazi/Siswati/Seswati', native: '' },
	{ english: 'Swedish', native: '' },
	{ english: 'Syriac', native: '' },

	{ english: 'Tabasaran/Tabassaran', native: '' },
	{ english: 'Tachelhit', native: '' },
	{ english: 'Tagalog', native: '' },
	{ english: 'Tahitian', native: '' },
	{ english: 'Taiwanese Sign Language', native: '' },
	{ english: 'Tajik', native: '' },
	{ english: 'Takestani', native: '' },
	{ english: 'Talysh', native: '' },
	{ english: 'Tamil', native: '' },
	{ english: 'Tanacross', native: '' },
	{ english: 'Tangut', native: '' },
	{ english: 'Tarifit/Rifi/Riff Berber', native: '' },
	{ english: 'Tat/Tati', native: '' },
	{ english: 'Tatar', native: '' },
	{ english: 'Tausug', native: '' },
	{ english: 'Tehuelche', native: '' },
	{ english: 'Telugu', native: '' },
	{ english: 'Tetum', native: '' },
	{ english: 'Tepehua language', native: '' },
	{ english: 'Tepehuán language', native: '' },
	{ english: 'Thai', native: '' },
	{ english: 'Tharu', native: '' },
	{ english: 'Tibetan', native: '' },
	{ english: 'Tigre/Xasa', native: '' },
	{ english: 'Tigrinya', native: '' },
	{ english: 'Timbisha/Panamint', native: '' },
	{ english: 'Tiv', native: '' },
	{ english: 'Tlingit', native: '' },
	{ english: 'Tobian', native: '' },
	{ english: 'Toda', native: '' },
	{ english: 'Tok Pisin', native: '' },
	{ english: 'Tokelauan', native: '' },
	{ english: 'Tonga', native: '' },
	{ english: 'Tongan', native: '' },
	{ english: 'Torwali/Turvali', native: '' },
	{ english: 'Tregami', native: '' },
	{ english: 'Tsat', native: '' },
	{ english: 'Tsez/Dido', native: '' },
	{ english: 'Tshiluba/Luba-Kasai/Luba-Lulua', native: '' },
	{ english: 'Tsonga', native: '' },
	{ english: 'Tswana/Setswana', native: '' },
	{ english: 'Tu/Monguor', native: '' },
	{ english: 'Tuareg languages/Tamasheq', native: '' },
	{ english: 'Tulu', native: '' },
	{ english: 'Tumbuka', native: '' },
	{ english: 'Tupiniquim', native: '' },
	{ english: 'Turkish', native: '' },
	{ english: 'Turkmen', native: '' },
	{ english: 'Turoyo', native: '' },
	{ english: 'Tuvaluan', native: '' },
	{ english: 'Tuvan Tuvin/Tyvan', native: '' },

	{ english: 'Udihe/Ude/Udege', native: '' },
	{ english: 'Udmurt/Votyak', native: '' },
	{ english: 'Ukrainian', native: '' },
	{ english: 'Ukwuani-Aboh-Ndoni', native: '' },
	{ english: 'Ulch/Olcha', native: '' },
	{ english: 'Unserdeutsch/Rabaul Creole German', native: '' },
	{ english: 'Upper Sorbian', native: '' },
	{ english: 'Urdu', native: '' },
	{ english: 'Uripiv', native: '' },
	{ english: 'Urum', native: '' },
	{ english: 'Ute', native: '' },
	{ english: 'Uyghur/Uigur', native: '' },
	{ english: 'Uzbek', native: '' },

	{ english: 'Vafsi', native: '' },
	{ english: 'Valencian', native: '' },
	{ english: 'Valencian Sign Language', native: '' },
	{ english: 'Vasi-vari/Prasuni', native: '' },
	{ english: 'Venda/Tshivenda', native: '' },
	{ english: 'Venetian', native: '' },
	{ english: 'Veps', native: '' },
	{ english: 'Vietnamese', native: '' },
	{ english: 'Võro', native: '' },
	{ english: 'Votic/Votian', native: '' },

	{ english: 'Waddar', native: '' },
	{ english: 'Waigali/Kalasha-Ala', native: '' },
	{ english: 'Waima/Roro', native: '' },
	{ english: 'Wakhi', native: '' },
	{ english: 'Walloon', native: '' },
	{ english: 'Waray-Waray/Binisaya', native: '' },
	{ english: 'Washo', native: '' },
	{ english: 'Welsh', native: '' },
	{ english: 'Western Neo-Aramaic', native: '' },
	{ english: 'Wolane', native: '' },
	{ english: 'Wolof', native: '' },
	{ english: 'Wu', native: '' },

	{ english: 'Xhosa', native: '' },
	{ english: 'Xiang', native: '' },
	{ english: 'Xibe/Sibo', native: '' },
	{ english: 'Xipaya', native: '' },
	{ english: 'Xóõ', native: '' },

	{ english: 'Yaaku language', native: '' },
	{ english: 'Yaeyama language', native: '' },
	{ english: 'Yaghnobi', native: '' },
	{ english: 'Yakut', native: '' },
	{ english: 'Yankunytjatjara language', native: '' },
	{ english: 'Yanomami', native: '' },
	{ english: 'Yanyuwa', native: '' },
	{ english: 'Yapese', native: '' },
	{ english: 'Yaqui', native: '' },
	{ english: 'Yauma', native: '' },
	{ english: 'Yavapai', native: '' },
	{ english: 'Yazdi', native: '' },
	{ english: 'Yazgulyam/Yazgulami', native: '' },
	{ english: 'Yemenite Hebrew', native: '' },
	{ english: 'Yeni language', native: '' },
	{ english: 'Yevanic language', native: '' },
	{ english: 'Yi language', native: '' },
	{ english: 'Yiddish', native: '' },
	{ english: 'Yidgha', native: '' },
	{ english: 'Yogur', native: '' },
	{ english: 'Yokutsan languages', native: '' },
	{ english: 'Yonaguni language', native: '' },
	{ english: 'Yoruba language', native: '' },
	{ english: 'Yucatec Maya language', native: '' },
	{ english: 'Yucatec Maya Sign Language', native: '' },
	{ english: 'Yuchi language', native: '' },
	{ english: 'Yugur', native: '' },
	{ english: 'Yukaghir languages', native: '' },
	{ english: 'Yupik language', native: '' },
	{ english: 'Yurats language', native: '' },
	{ english: 'Yurok language', native: '' },

	{ english: 'Záparo', native: '' },
	{ english: 'Zapotec', native: '' },
	{ english: 'Zazaki', native: '' },
	{ english: 'Zulu', native: '' },
	{ english: 'Zuñi/Zuni', native: '' },
	{ english: 'Zway/Zay', native: '' },
];
