export type SocialLink = {
	name: string;
	icon: string;
	link?: string;
};

export const socialLinksOptions = [
	{ name: 'ArtStation', icon: '', default: '' },
	{ name: 'Behance', icon: '', default: '' },
	{ name: 'Bitbucket', icon: '', default: '' },
	{ name: 'DeviantArt', icon: '', default: '' },
	{ name: 'Discord', icon: '', default: '' },
	{ name: 'Dribbble', icon: '', default: '' },
	{ name: 'Facebook', icon: '', default: '' },
	{ name: 'Fansly', icon: '', default: '' },
	{ name: 'Flickr', icon: '', default: '' },
	{ name: 'GitHub', icon: '', default: '' },
	{ name: 'GitLab', icon: '', default: '' },
	{ name: 'IndieGoGo', icon: '', default: '' },
	{ name: 'Instagram', icon: '', default: '' },
	{ name: 'Kick', icon: '', default: '' },
	{ name: 'Kickstarter', icon: '', default: '' },
	{ name: 'Ko-fi', icon: '', default: '' },
	{ name: 'LinkedIn', icon: '', default: '' },
	{ name: 'Mastodon', icon: '', default: '' },
	{ name: 'Medium', icon: '', default: '' },
	{ name: 'OnlyFans', icon: '', default: '' },
	{ name: 'Patreon', icon: '', default: '' },
	{ name: 'PayPal', icon: '', default: '' },
	{ name: 'Pinterest', icon: '', default: '' },
	{ name: 'Pixiv', icon: '', default: '' },
	{ name: 'Quora', icon: '', default: '' },
	{ name: 'Reddit', icon: '', default: '' },
	{ name: 'Renren', icon: '', default: '' },
	{ name: 'Rumble', icon: '', default: '' },
	{ name: 'Signal', icon: '', default: '' },
	{ name: 'Slack', icon: '', default: '' },
	{ name: 'Snapchat', icon: '', default: '' },
	{ name: 'Spotify', icon: '', default: '' },
	{ name: 'SoundCloud', icon: '', default: '' },
	{ name: 'Stack Overflow', icon: '', default: '' },
	{ name: 'Steam', icon: '', default: '' },
	{ name: 'SubscribeStar', icon: '', default: '' },
	{ name: 'Substack', icon: '', default: '' },
	{ name: 'Telegram', icon: '', default: '' },
	{ name: 'TikTok', icon: '', default: '' },
	{ name: 'Tumblr', icon: '', default: '' },
	{ name: 'Twitch', icon: '', default: '' },
	{ name: 'Twitter', icon: '', default: '' },
	{ name: 'Website', icon: '', default: '' },
	{ name: 'WeChat', icon: '', default: '' },
	{ name: 'Weibo', icon: '', default: '' },
	{ name: 'WhatsApp', icon: '', default: '' },
	{ name: 'YouTube', icon: '', default: '' },
];
